version: "3.9"
services:
    twitch_chat_reader:
        container_name: twitch_reader
        build: 
            context: ./twitch-chat-reader
        networks: 
            stream-net:
                aliases:
                    - twitchreader
        env_file: ./twitch-chat-reader/credentials.env
        ports: 
            - "6667:6667"
        depends_on:
            - backend
    
    chat_input_handler:
        container_name: chat_input_handler
        build: 
            context: ./chat-input-handler
        environment:
            - TWITCH_READER=twitchreader
            - BACKEND_NAME=backend
        networks: 
            stream-net:
                aliases:
                    - chathandler
        depends_on:
            - twitch_chat_reader
            - backend

    backend:
        container_name: backend
        build:
            context: ./backend
        environment:
            - DB_API_NAME=db_api
            - DB_API_PORT=1337
        networks:
            stream-net:
                aliases:
                    - backend

    db_api:
        container_name: db_api
        build:
            context: ./db-api
        networks:
            stream-net:
                aliases:
                    - db_api

networks:
    stream-net:
        driver: bridge
        name: stream-net
