version: "3.9"
services:
    twitch_chat_reader:
        container_name: twitch_reader
        build: 
            context: ./twitch-chat-reader
        networks: 
            stream-net:
                aliases:
                    - twitchreader
        env_file: ./twitch-chat-reader/credentials.env
        ports: 
            - "6667:6667"
        depends_on:
            - chat_input_handler
            - backend
    
    chat_input_handler:
        container_name: chat_input_handler
        build: 
            context: ./chat-input-handler
        environment:
            - TWITCH_READER=twitchreader
            - DB_API=db_api
            - BACKEND_NAME=backend
            - BACKEND_PORT=1336
        networks: 
            stream-net:
                aliases:
                    - chathandler
        restart: on-failure
        ports:
            - "443"
        depends_on:
            - backend

    backend:
        container_name: backend
        build:
            context: ./backend
        environment:
            - DB_API_NAME=db_api
            - DB_API_PORT=1337
        ports:
            - "1336:1336"            
        restart: on-failure
        networks:
            stream-net:
                aliases:
                    - backend
        depends_on:
            - db_api

    db_api:
        container_name: db_api
        build:
            context: ./db-api
        environment:
            - DB_USER=postgres
            - DB_PASS=password
            - DB_NAME=livestream
        restart: on-failure
        ports:
            - "1337:1337"
        networks:
            stream-net:
                aliases:
                    - db_api
        depends_on:
            - db

    db:
        container_name: database
        image: postgres
        environment:
            - POSTGRES_USER=postgres 
            - POSTGRES_PASSWORD=password
            - POSTGRES_DB=livestream
        ports:
            - "5432:5432"
        networks:
            stream-net:
                aliases:
                    - database
        volumes:
            - postgres_data:/var/lib/postgresql/13/main

volumes:
    postgres_data:

networks:
    stream-net:
        driver: bridge
        name: stream-net
