version: "3.9"
services:
    twitch_chat_reader:
        container_name: twitch_reader
        build: 
            context: ./twitch-chat-reader
        networks: 
            stream-net:
                aliases:
                    - twitch_reader
        env_file: ./twitch-chat-reader/credentials.env
        ports: 
            - "6667:6667"
        depends_on:
            - chat_input_handler
    
    chat_input_handler:
        container_name: chat_input_handler
        build: 
            context: ./chat-input-handler
        environment:
            - TWITCH_READER=twitch_reader
            - DB_API=db_api
            - BACKEND=backend
        networks: 
            stream-net:
                aliases:
                    - chat_input_handler
        restart: on-failure
        ports:
            - "443"
        depends_on:
            - backend

    chat_output_handler:
        container_name: chat_output_handler
        build:
            context: ./chat-output-handler
        environment:
            - BACKEND=backend
            - TWITCH_QUEUE=twitch_output
        networks:
            stream-net:
                aliases:
                    - chat_output_handler
        restart: on-failure
        depends_on:
            - backend

    backend:
        container_name: backend
        build:
            context: ./backend
        environment:
            - DB_API_NAME=db_api
            - DB_API_PORT=1337
            - CHAT_OUTPUT=chat_output
        ports:
            - "1336:1336"            
        restart: on-failure
        networks:
            stream-net:
                aliases:
                    - backend
        depends_on:
            - db_api

    db_api:
        container_name: db_api
        build:
            context: ./db-api
        environment:
            - DB_USER=postgres
            - DB_PASS=password
            - DB_NAME=livestream
        restart: on-failure
        ports:
            - "1337:1337"
        networks:
            stream-net:
                aliases:
                    - db_api
        depends_on:
            - db

    db:
        container_name: database
        image: postgres
        environment:
            - POSTGRES_USER=postgres 
            - POSTGRES_PASSWORD=password
            - POSTGRES_DB=livestream
        ports:
            - "5432:5432"
        networks:
            stream-net:
                aliases:
                    - database
        volumes:
            - postgres_data:/var/lib/postgresql/13/main

volumes:
    postgres_data:

networks:
    stream-net:
        driver: bridge
        name: stream-net
